// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2IkEDYEH24SkIC6s2SFAEYnDBgWD0JmM',
    appId: '1:200849814262:web:e14dbe7bbaaf847bbf72d7',
    messagingSenderId: '200849814262',
    projectId: 'compas-cs',
    authDomain: 'compas-cs.firebaseapp.com',
    storageBucket: 'compas-cs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhr1mmSYYElhiZvOvlnufXVA7sWvdwF3E',
    appId: '1:200849814262:android:e0296ce0941ea3d3bf72d7',
    messagingSenderId: '200849814262',
    projectId: 'compas-cs',
    storageBucket: 'compas-cs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD75ug2CT68etOwbCN-pC7vamOed_a5VI',
    appId: '1:200849814262:ios:1eba766b51304ae7bf72d7',
    messagingSenderId: '200849814262',
    projectId: 'compas-cs',
    storageBucket: 'compas-cs.appspot.com',
    iosBundleId: 'com.example.csCompas',
  );
}
